### ISSUE TITLE
RenderToolbox3InstallationTest() fails

### ISSUE THREAD

**Issue by marksheinin** [RenderToolbox3/RenderToolbox3#43]
Hi,
I installed all the components by the 'book' (built everything from source). I try to run RenderToolbox3InstallationTest() and Mitsuba fails giving the following error:

"/home1/markshe/Documents/MATLAB/render-toolbox/MakeMaterialSphere/scenes/Mitsuba/materialSphereMatte.xml" (near line 55): Error while creating object: main [spectrum.cpp:212] Spectrum::getBinCoverage() is not supported when Mitsuba is configured for RGB-based rendering"

I used -DSPECTRUM_SAMPLES=31 as needed while building mitsuba.

Using Matlab R2015b on Ubuntu 14.04

Thanks in advance.

**Comment by benjamin-heasly** [comment]
Hi,

Do you mind double checking some things?  I ask because it seems fairly odd that Mitsuba would complain about RGB mode after being built with `-DSPECTRUM_SAMPLES=31`.  That would be a deep Mitsuba bug, rather than a RenderToolbox3 bug.

First, can you double check your build log for the SPECTRUM_SAMPLES parameter?

```
cd your-mitsuba-folder
cat config.log | grep "SPECTRUM_SAMPLES"
```

Does the log say `-DSPECTRUM_SAMPLES=31`?

Second, can you double check that the Mitsuba executable you're invoking from RenderToolbox3 is the same one you built from source?  This would be in your copy of `RenderToolbox3ConfigurationTemplate`, and you should have something like this near line 71:

```
    myMistubaExecutable = 'your-mitsuba-folder/dist/mitsuba';
    myMistubaImporter = 'your-mitsuba-folder/dist/mtsimport';
```

If all that looks good, there may be one more thing.  It could be that you're indeed using your own executable, but linking at runtime to a default RGB installation of the Mitsuba library.  If that's the case, we can try explicitly pointing the executable at your spectral version of the library.  This would be one more line added to your RenderToolbox3 configuration file.

I updated 'RenderToolbox3ConfigurationTemplate' to show what this line should look like.  [Please see here](https://github.com/RenderToolbox3/RenderToolbox3/blob/master/Utilities/RenderToolbox3ConfigurationTemplate.m#L79).

Any help of this help?

**Comment by benjamin-heasly** [comment]
Version 3 will change the installation process with new dependencies and new ways to get executable binaries. So we will be changing the installation instructions and will revisit this installation test.

**Comment by benjamin-heasly** [comment]
Closing this issue.  It should be addressed in RenderToolbox4:
  https://github.com/RenderToolbox/RenderToolbox4
